#controllers:
#    resource: ../src/Controller/
#    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

get_index_products:
    path: /products
    methods: ["GET"]
    controller: playddd.product_controller::getIndex